% graphical lasso (foti et al. 2016, eq 1)
function [Theta, info] = glasso(S,lambda)

  cvx_begin
    variable Theta(p,p) symmetric
    minimize ( -log_det(Theta) + trace(Theta*S) + ...
      lambda*norm(Theta(triu_mask),1) )
  cvx_end
  
  obj = [-log_det(Theta), ...
    trace(Theta*S), ...
    lambda*norm(Theta(triu_mask),1)];

  info = struct( ...
    'obj',         obj, ...
    'cvx_status',  cvx_status, ...
    'cvx_slvtol',  cvx_slvtol, ...
    'cvx_cputime', cvx_cputime);

end